apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-mysql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-mysql-service
  template:
    metadata:
      labels:
        app: faculty-mysql-service
    spec:
      containers:
        - name: faculty-mysql-service
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: ex3
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: pass123
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-mysql-service
spec:
  type: ClusterIP
  selector:
    app: faculty-mysql-service
  ports:
    - port: 3306
      targetPort: 3306