apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-filiere-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-filiere-service
  template:
    metadata:
      labels:
        app: faculty-filiere-service
    spec:
      containers:
        - name: faculty-filiere-service
          image: faculty_management-faculty-filiere-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://faculty-discovery-service.default.svc.cluster.local:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-filiere-service
spec:
  type: LoadBalancer
  selector:
    app: faculty-filiere-service
  ports:
    - port: 8081
      targetPort: 8081